### ISSUE TITLE
BUG: 11g SQL Script Accessing v$diag_alert_ext that do not exists

### ISSUE THREAD

**Issue by ersantosnet** [GoogleCloudPlatform/database-assessment#102]
### Description

11g SQL Script accessing v$diag_alert_ext that do not exists in this DBVersion

### Priority

priority:0

**Comment by smancinijr** [comment]
Based on MOS note
How To Query Oracle X$ Tables From Another User Other Than SYS? (Doc ID 2009144.1)
and in some testing, we can't substitute the original view.

"grant select any dictionary" and "grant select any table"  also doesn't work.
