### ISSUE TITLE
BUG: V_DS_dbsummary view can return multiple rows if one or more RAC nodes are down during collection.

### ISSUE THREAD

**Issue by wpuziewicz** [GoogleCloudPlatform/database-assessment#191]
### Description

If a data collection is run on RAC where one instance is down, this view will return multiple records.

### Priority

priority:3

### What oracle database version are you seeing the problem on?

All

**Comment by cofin** [comment]
@smpawar @wpuziewicz has this been addressed?

**Comment by smpawar** [comment]
@cofin No I didn't. @wpuziewicz please suggest.

**Comment by wpuziewicz** [comment]
This may not be an issue anymore after the code reorg.  Will test and verify.

**Comment by cofin** [comment]
closed by #246
