### ISSUE TITLE
ER: Add support for $ORACLE_HOME/OPatch/opatch lsinventory -detail and more patch level information

### ISSUE THREAD

**Issue by smpawar** [GoogleCloudPlatform/database-assessment#212]
### Enhancement Request Details

As a end user I want to have this information in order to improve migration effectiveness using waverunner. 
Once we are able to communicate with API between the 2 tools , then waverunner will pull this information as part of the "Source Database Inventory" lookup step for validation phase . This will be used for creating the instance accordingly.  

Check for binary patches applied at Oracle grid and database homes

For grid and database homes:

$ORACLE_HOME/OPatch/opatch lsinventory -detail

For grid home only:

$ crsctl query crs releasepatch

Check for patches applied at database level

For 11g and below versions:

SELECT TO_CHAR(action_time, 'mm/dd/rr hh24:mi') AS "Time",
       action                                   AS "Action",
       namespace                                AS "Namespace",
       version                                  AS "Version",
       id                                       AS "ID",
       comments                                 AS "Comments"
FROM   sys.registry$history
ORDER  BY action_time; 

For versions 12.1.0.1 and above, datapatch was introduced and used to apply patches instead of catbundle.sql. The information is now in DBA_REGISTRY_SQLPATCH

SELECT TO_CHAR(action_time, 'DD-MON-YYYY HH24:MI:SS') AS action_time,
       action,
       status,
       description,
       version,
       patch_id,
       bundle_series
FROM   sys.dba_registry_sqlpatch
ORDER by action_time;

### Version

None

### What oracle database version are you seeing the problem on?

12c and above

### Which sql script version ?

Other

**Comment by cofin** [comment]
Closed by #246
