### ISSUE TITLE
BUG: change the extract to use v$container

### ISSUE THREAD

**Issue by smpawar** [GoogleCloudPlatform/database-assessment#222]
### Description

This is to support situations where objects are created in the CDB instead of PDBs.

### Version

v4 (Default)

### Priority

priority:3

### What oracle database version are you seeing the problem on?

12c and above

### Which sql script version ?

None

**Comment by cofin** [comment]
@smpawar do you have more details on this one?  If not, let's close this one and re-open if it comes up again.
