### ISSUE TITLE
DOC: 

### ISSUE THREAD

**Issue by ajai91** [GoogleCloudPlatform/database-assessment#259]
### Documentation change request Details?

script comes out with an error.

### Version

1.0.2 (Default)

### What oracle database version are you seeing the problem on?

12c and above

### Which sql script version ?

2.0.4

### Relevant log output

```shell
oraown@l****1 PSTP1 /tmp/Google_tool_script/log >cat opdb__190_4.3.2_l****1.****.******.com_PSTP1_PSTP1_051023115423_errors.log
SELECT  sys.dbms_qopatch.get_opatch_lsinventory
```

**Comment by wpuziewicz** [comment]
Hi ajai91,

Did you get any errors when running the grants_wrapper.sql script?  
Did you run collect-data.sh with the UseDiagnostics or NoDiagnostics parameter?

Thanks

**Comment by cofin** [comment]
`opatch` should be disabled by default
